---
title: "project2"
author: "anon"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(aaltobda)
library(rstan)
library(loo)
library(latex2exp)
library(bayesplot)
rstan_options (javascript = FALSE)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
findings_df <- read.csv("findings.tsv_type.csv")
findings_df$journal = "findings"

main_df <- read.csv("main.tsv_type.csv")
main_df$journal = "main"



df <- rbind(findings_df, main_df)
head(df)
```

```{r}
sizes <- c(nrow(main_df), nrow(findings_df))
data <- rbind(main_df, findings_df)$Citation
sizes
```

```{r}
ggplot(df, aes(Citation, color=journal, fill=journal)) +
  geom_density(alpha=0.2) +
  coord_cartesian(xlim=c(0, 50))
```


# Citation-Only Model (closed form conjugate solution)

```{r}
sample_closed_draws <- function(samples, n_draws, alpha = 0.001, beta = 0.001) {
  n <- length(samples)
  closed_draws <- rgamma(n_draws, alpha + sum(samples), beta + n)  
  return(data.frame(lambda=closed_draws))
}

ppc_draws <- function(n_posterior_draws, y, alpha, beta) {
  acc = c()
  for(i in 1:n_posterior_draws) {
    posterior_draws <- sample_closed_draws(y, length(y), alpha, beta)
    ypreds <- sapply(posterior_draws$lambda, function(lambda) rpois(1, lambda))
    acc <- append(acc, ypreds)
  }
  return(matrix(acc, ncol=length(y)))
}
```

```{r}

main_ypred <- ppc_draws(25, main_df$Citation, alpha = 0.001, beta = 0.001)
ppc_dens_overlay(main_df$Citation, main_ypred) + xli¢m(0, 50) + ggtitle("PPC Main Simple Non-informative") + theme(text = element_text(size = 16, family="sans"))   

find_ypred <- ppc_draws(25, findings_df$Citation, alpha = 0.001, beta = 0.001)
ppc_dens_overlay(findings_df$Citation, find_ypred) + xlim(0, 50) + ggtitle("PPC Findings Simple Non-informative¢") + theme(text = element_text(size = 16, family="sans"))   
```

# Citation-Only Model (MCMC)

## Non-informative priors

```{r}
simple_model_data <- list(N = length(data),
                   sizes = sizes,
                   J = 2,
                   y = data,
                   draws = 2000)

simple_non <- stan(file = "stan_models/simple-non.stan", 
            data = simple_model_data,
            chains = 4,
            iter = 3000,
            warmup = 2000)
simple_non
```

## Weakly-informative priors

```{r}
simple_weak <- stan(file = "stan_models/simple-weak.stan", 
            data = simple_model_data,
            chains = 4,
            iter = 3000,
            warmup = 2000)
simple_weak
```


# Citation & Paper Length Model

## Separate

```{r}
# ####### Citation + length model separate #######
# findings_df <- findings_df[quantile(findings_df$Citation) < 75, ]
# main_df <- main_df[quantile(main_df$Citation) < 75, ]

df <- rbind(main_df, findings_df)
  
y2 <- as.numeric(factor(df$type)) - 1
sizes <- c(nrow(main_df), nrow(findings_df))
separate_data <- list(
  N = nrow(df),
  sizes = sizes,
  J = 2,
  y1 = df$Citation,
  y2 = y2,
  is_long = y2,
  draws = 2000
)

separate <- stan(file = "stan_models/citation-length-separate.stan", 
            data = separate_data,
            chains = 4,
            iter = 4000,
            warmup = 2000)
separate
```

```{r}
draws <- as.data.frame(separate)

# group together diff. indicies e.g. lambda[1], lambda[2] -> lambda[1,1]
params <- extract(separate, permuted=TRUE)
dim(params$main_ypred)
dim(main_df)
```

```{r}
main_y <- main_df$Citation
find_y <- findings_df$Citation

main_ypred <- params$main_ypred
find_ypred <- params$findings_ypred

ppc_dens_overlay(main_y, main_ypred[1:25, 1:length(main_y)]) + xlim(0, 50)
ppc_dens_overlay(find_y, find_ypred[1:25, 1:length(find_y)]) + xlim(0, 50)
```

## Hierarchical
```{r}
# Citation + length model hierarchical
# findings_df <- findings_df[quantile(findings_df$Citation) < 75, ]
# main_df <- main_df[quantile(main_df$Citation) < 75, ]

df <- rbind(findings_df, main_df)
  
y2 <- as.numeric(factor(df$type)) - 1
sizes <- c(nrow(main_df), nrow(findings_df))
hierarchical_data <- list(
  N = nrow(df),
  sizes = sizes,
  J = 2,
  y1 = df$Citation,
  y2 = y2,
  is_long = y2,
  draws = 2000
)

hierarchical <- stan(file = "stan_models/citation-length-hierarchical.stan", 
            data = hierarchical_data,
            chains = 4,
            iter = 4000,
            warmup = 2000)

hierarchical
```

```{r}
# group together diff. indicies e.g. lambda[1], lambda[2] -> lambda[1,1]
hierarchical_extracts <- extract(hierarchical, permuted=TRUE)
dim(hierarchical_extracts$main_ypred)
dim(main_df)
```

```{r}
main_y <- main_df$Citation
find_y <- findings_df$Citation

main_ypred <- hierarchical_extracts$main_ypred
find_ypred <- hierarchical_extracts$findings_ypred

ppc_dens_overlay(main_y, main_ypred[1:25, 1:length(main_y)]) + xlim(0, 50)
ppc_dens_overlay(find_y, find_ypred[1:25, 1:length(find_y)]) + xlim(0, 50)
```

# Comparing models

```{r}
loo_simple_non = loo(simple_non, save_psis = TRUE)
loo_simple_weak = loo(simple_weak, save_psis = TRUE)
loo_separate = loo(separate, save_psis = TRUE)
loo_hierarchical = loo(hierarchical, save_psis = TRUE)
```

## Getting the elpd LOO

```{r}
loo_simple_non[1]$estimates[1]
loo_simple_weak[1]$estimates[1]
loo_separate[1]$estimates[1]
loo_hierarchical[1]$estimates[1]
```

## Plot $\hat{k}$values

```{r}
# Simple model - non-informative priors
plot(loo_simple_non)
```
```{r}
# Simple model - weakly-informative priors
plot(loo_simple_weak)
```

```{r}
# Separate model
plot(loo_separate)
```

```{r}
# Hierarchical model
plot(loo_hierarchical)
```

## Compute the effective number of parameters $p_\text{eff}$

```{r}
print(loo_simple_non$p_loo)
print(loo_simple_weak$p_loo)
print(loo_separate$p_loo)
print(loo_hierarchical$p_loo)
```

